# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-26 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_task_tasklogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
